#local 환경
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/mars
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none # 테이블 drop 후 자동 생성
    properties:
      hibernate:
        #         show_sql: true # 시스템 아웃으로 sql 출력
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug # 로거를 통해 sql 출력
    org.hibernate.type: trace # 파라미터 로거남기기
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: trace # 캐시 로그 남기기

kis:
  api:
    grant_type: client_credentials
    app_key: PSvmItgnWGaKewHlPjtS37dBrne7NXFWPfVF
    app_secret: YaLtdbOxGxzrztwLGbPoXo/c+X892jML3ucRYDELTQ/MbQRXbS2qcyjh6rhyCKSlh9NQ3bBXGXQEZE3nMivPsFe8lLgDqAlmfuHQlYnbB9F3l1GoeLMG/C/sy4vzfd8OxUXf+u2CAG/UOaJEcH7TtQ8xSZ6tE6St4uM4Oon2ooFm6so0epc=
    access_token : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjU2N2Y4NDZmLTE1YTgtNDdmNy1iOWIyLWExY2Q3YTNlMTY3YyIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc0MTQxNTMxNSwiaWF0IjoxNzQxMzI4OTE1LCJqdGkiOiJQU3ZtSXRnbldHYUtld0hsUGp0UzM3ZEJybmU3TlhGV1BmVkYifQ.O5Q4481YyHv5NlAr45V7CQ7bNdm3IO5hx7YEw7UMWNmbOsQNbGGSeZOE5DXLlJRel7ZrUBtHS91P_C9yE_PRYA

firebase:
  credentials:
    path: firebase/mars-1a3f5-firebase-adminsdk-fbsvc-db14567537.json

notification:
  stock:
    title: "📈 주식 변동 알림"
    message: "변동률은 %.2f%% 이상 변동하였습니다."

