-- 주식 정보 데이터 삽입
INSERT INTO stock_info (stock_code, stock_name) VALUES ('035420', 'NAVER');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('005930', '삼성전자');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('035720', '카카오');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('000660', 'SK hynix');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('005380', '현대차');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('051910', 'LG화학');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('005490', 'POSCO');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('000270', '기아');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('035000', '셀트리온');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('068270', '셀트리온헬스케어');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('036570', '한국전력');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('017670', 'SK텔레콤');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('012330', '롯데케미칼');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('032640', 'KB금융');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('005720', '한화생명');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('006800', '삼성생명');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('011200', '삼성화재');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('086790', '우리금융지주');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('033780', 'KT&G');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('033520', 'LG전자');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('051900', 'LG디스플레이');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('035250', 'CJ ENM');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('000810', 'SK네트웍스');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('086280', '한온시스템');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('012750', '현대모비스');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('021240', '대우건설');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('086980', '대림산업');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('009150', '삼성전기');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('010950', 'SK이노베이션');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('017800', '한화에어로스페이스');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('032830', '롯데하이마트');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('018260', '현대건설');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('018880', 'LG유플러스');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('003550', '두산중공업');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('071050', '한미약품');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('047050', '현대글로비스');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('020000', '쌍용차');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('009830', '하나금융지주');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('096770', '삼성SDI');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('004170', '아모레퍼시픽');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('003670', 'LG생활건강');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('010130', '이마트');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('003000', 'CJ제일제당');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('041190', '삼성증권');
INSERT INTO stock_info (stock_code, stock_name) VALUES ('033180', '한국항공우주');


-- Member 테이블에 데이터 삽입
INSERT INTO member (name, email, status, last_access_time, join_time) VALUES ('홍길동', 'hong@example.com', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);